FROM node:15.6-alpine

WORKDIR /app

# COPY package.json /app/package.json

# RUN npm install

# Устнановка сервера
RUN npm install -g serve

COPY . /app

EXPOSE 3000

CMD ["killall", "-9", "node"]

RUN npm run build

# Запуск сервера на 3000 порту.
CMD ["serve", "-s", "build", "-l", "3000"]
