version: 2.1

jobs:
  deploy:
    docker:
      # Ubuntu 20.04 образ
      - image: 'cimg/base:2021.01'
    steps:
      - add_ssh_keys
      - run:
          name: Добавление ssh known_hosts
          command: |
            mkdir -p ~/.ssh/
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Актуализация кодовой базы
          command: |
            echo $SSH_USER@$SSH_HOST
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail && git pull"
      - run:
          name: Экспортирование переменных и запуск тестов
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail/backend && export REDIS_HOST=localhost REDIS_DB=0 REDIS_PORT=6379 REDIS_PASSWORD=foobared && python3 -m pytest --junitxml=test-results/junit.xml"
      - run:
          name: Копирование файла с сервера в контейнер circleci
          command: |
            mkdir -p test-results/
            scp $SSH_USER@$SSH_HOST:/home/alex/bustail/backend/test-results/junit.xml ~/project/test-results/

      # Параметр для загрузки результатов в Tests GUI circleci
      - store_test_results:
          path: test-results

      # Сохрананение артифакта (обычный файл) о завершении теста.
      - store_artifacts:
          path: test-results

      - run:
          name: Остановка контейнеров и чиста образов
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail && docker-compose -f $CFG_NAME down"

      - run:
          name: Развертывание контейнеров
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail && docker-compose -f $CFG_NAME up -d --build"
      - run:
          name: Быстрый просмотр логов о состоянии системы
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail && docker-compose -f $CFG_NAME logs --tail="20""

workflows:
  version: 2.1
  build-and-deploy-prod:
    jobs:
      - deploy:
          context:
            - Production
          filters:
            branches:
              only:
                - main
